[[text_config]]
text = "＊このIDを呼び出すことは不可能だよ．どうやって表示したの？"
next = 0

[[text_config]]
text = "＊１番のテキストだよ～"
next = 2

[[text_config]]
text = "＊２番のテキストだよ～"
next = 3

[[text_config]]
text = "＊３番のテキストだよ～"
next = 4

[[text_config]]
text = "＊４番のテキストだよ～"
next = 5

[[text_config]]
text = "＊５番のテキストだよ～"
next = 0
